# Generated by Django 4.1 on 2022-09-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20220831_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': False},
        ),
    ]
